### ISSUE TITLE
十年崩三，不请自来(狗头) - 能整理下语音和台词的对照表吗

### ISSUE THREAD

**Issue by zthxxx** [zer0e/bh3-rainbow-fart#1]
自定义或者自己想调整的时候，有个台词对照表会方便很多，要不基本改不动

想要一个像这样的语音台词对照表

https://github.com/zthxxx/kugimiya-rainbow-fart/blob/master/resource.csv

![image](https://user-images.githubusercontent.com/15135943/86003412-508a3a00-ba44-11ea-8d33-8cad710cd018.png)

**Comment by zer0e** [comment]
这两天会整理！

**Comment by zer0e** [comment]
> 自定义或者自己想调整的时候，有个台词对照表会方便很多，要不基本改不动
> 
> 想要一个像这样的语音台词对照表
> 
> https://github.com/zthxxx/kugimiya-rainbow-fart/blob/master/resource.csv
> 
> ![image](https://user-images.githubusercontent.com/15135943/86003412-508a3a00-ba44-11ea-8d33-8cad710cd018.png)

已添加角色与语音台词对照表
